function [TableOut,DataGrouped] = loadGaitRetrainingExcel(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  GAITRETRAININGDATASETROTATED = IMPORTFILE(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  GAITRETRAININGDATASETROTATED = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  GAITRETRAININGDATASETROTATED = IMPORTFILE(FILE, SHEET, DATALINES)
%  reads from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  GaitRetrainingDatasetRotated = importfile("W:\OA_GaitRetraining\DATA\CompiledData\GaitRetrainingDatasetRotated.xlsx", "Sheet1", [2, 69]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Jun-2021 14:38:42

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 69];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 89);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":CK" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["subject", "age", "KL", "gender", "alignment", "group", "BMI_wk07", "BMI_wk11", "BMI_wk25", "BMI_wk39", "BMI_wk52", "Compliance_wk07", "Compliance_wk11", "Compliance_wk25", "Compliance_wk39", "Compliance_wk52", "date_wk02", "date_wk07", "date_wk11", "date_wk25", "date_wk39", "date_wk52", "FPA_error_wk07", "FPA_error_wk11", "FPA_error_wk25", "FPA_error_wk39", "FPA_error_wk52", "FPA_natural_wk01", "KAM_peak_natural_FPA_wk01", "KAM_peak_target_FPA_wk01", "KAM_peak_target_FPA_wk07", "KAM_peak_target_FPA_wk11", "KAM_peak_target_FPA_wk25", "KAM_peak_target_FPA_wk39", "KAM_peak_target_FPA_wk52", "KOOS_wk02", "KOOS_wk07", "KOOS_wk11", "KOOS_wk25", "KOOS_wk39", "KOOS_wk52", "NRS_lat_wk02", "NRS_lat_wk07", "NRS_lat_wk11", "NRS_lat_wk25", "NRS_lat_wk39", "NRS_lat_wk52", "NRS_med_wk02", "NRS_med_wk07", "NRS_med_wk11", "NRS_med_wk25", "NRS_med_wk39", "NRS_med_wk52", "NRS_PF_wk02", "NRS_PF_wk07", "NRS_PF_wk11", "NRS_PF_wk25", "NRS_PF_wk39", "NRS_PF_wk52", "steps_wk02", "steps_wk07", "steps_wk11", "steps_wk25", "steps_wk39", "steps_wk52", "WOMAC_function_wk02", "WOMAC_function_wk07", "WOMAC_function_wk11", "WOMAC_function_wk25", "WOMAC_function_wk39", "WOMAC_function_wk52", "WOMAC_pain_wk02", "WOMAC_pain_wk07", "WOMAC_pain_wk11", "WOMAC_pain_wk25", "WOMAC_pain_wk39", "WOMAC_pain_wk52", "T1rho_med_wk01", "T1rho_lat_wk01", "T2_med_wk01", "T2_lat_wk01", "T1rho_med_wk52", "T1rho_lat_wk52", "T2_med_wk52", "T2_lat_wk52", "T1rho_med_voxelwise_delta", "T1rho_lat_voxelwise_delta", "T2_med_voxelwise_delta", "T2_lat_voxelwise_delta"];
opts.VariableTypes = ["double", "double", "double", "categorical", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "string", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["date_wk02", "date_wk07", "date_wk11", "date_wk25", "date_wk39"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["gender", "group", "date_wk02", "date_wk07", "date_wk11", "date_wk25", "date_wk39", "date_wk52"], "EmptyFieldRule", "auto");

% Import the data
TableOut = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":CK" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    TableOut = [GaitRetrainingDatasetRotated; tb]; %#ok<AGROW>
end

indsC = find(TableOut.group=='C') ;
indsI = find(TableOut.group=='I') ;

DataGrouped.Intervention = TableOut(indsI,:) ;
DataGrouped.Control = TableOut(indsC,:) ;

end





