function [data structReturn] = loadNRS(workbookFile, subjects, sheetName, RANGE)
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   cell array.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,RANGE) reads from the specified worksheet
%   and from the specified RANGE. Specify RANGE using the syntax
%   'C1:C2',where C1 and C2 are opposing corners of the region.%
% Example:
%   NRS = importfile('NRS.xlsx','Sheet1','A1:V22');
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/08/16 17:01:28

%% Input handling

% If no sheet is specified, read first sheet
if ~exist('sheetName','var') || isempty(sheetName)
    sheetName = 1;
end

% If no RANGE is specified, read all data
if ~exist('RANGE','var') || isempty(RANGE)
    RANGE = '';
end

%% Import the data
[~, ~, data] = xlsread(workbookFile, sheetName, RANGE);
dataRaw = data ;
data(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),data)) = {''};

subjectCol = strmatch('Subject',data(2,:)) ;
if ~exist('subjects') || isempty(subjects)
    subjects = [data{3:end,subjectCol}]
end

rowsToAnalyze = find(ismember([data{3:end,subjectCol}],subjects))+2 ;

inds.Medial = strmatch('Medial',data(1,:)) ;
inds.PF = strmatch('Patellofemoral',data(1,:)) ;
inds.Lateral = strmatch('Lateral',data(1,:)) ;

structReturn.week = data(2,inds.Medial:inds.PF-1) ;
structReturn.Medial = cell2mat(dataRaw(rowsToAnalyze,inds.Medial:inds.Medial+length(structReturn.week)-1)) ;
structReturn.Lateral = cell2mat(dataRaw(rowsToAnalyze,inds.Lateral:inds.Lateral+length(structReturn.week)-1)) ;
structReturn.PF = cell2mat(dataRaw(rowsToAnalyze,inds.PF:inds.PF+length(structReturn.week)-1)) ;
structReturn.subjects = cell2mat(data(rowsToAnalyze,1)) ;

for i = 1:length(structReturn.week)
    eval(['structReturn.weekInds.' structReturn.week{i} '= ' num2str(strmatch(structReturn.week(i),structReturn.week,'exact')) ';'])
end

