function [OUT] = loadMRIspreadsheet(workbookFile,subjects)
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   cell array.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,RANGE) reads from the specified worksheet
%   and from the specified RANGE. Specify RANGE using the syntax
%   'C1:C2',where C1 and C2 are opposing corners of the region.%
% Example:
%   DemographicInformation = importfile('DemographicInformation.xlsx','Sheet1','A2:E22');
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/08/16 17:09:08

%% Input handling

sheetNames = {'PixelwiseDifference','LongitudinalValues'} ;
if ~exist('subjects')
    subjects = 1:169 ;
end

%% Import the data

[~, ~, data_PW] = xlsread(workbookFile,sheetNames{1}); % pixelwise
[~, ~, data_LV] = xlsread(workbookFile,sheetNames{2}); % longitudinal values
data_LV(cellfun(@(x) ~isnumeric(x) && contains(x,'/'),data_LV)) = {nan};

%% 
nSubs = length(subjects) ;
subjectRow = strmatch('Subject_Number',data_PW(1,:)) ;
sub_PW = cell2mat(data_PW(2:end,subjectRow)) ;
subjectRow = strmatch('Subject_Number',data_LV(1,:)) ;
sub_LV = cell2mat(data_LV(2:end,subjectRow)) ;
weekRow = strmatch('Week',data_LV(1,:)) ;
week_LV = cell2mat(data_LV(2:end,weekRow)) ;

T1p_med_row_LV = strmatch('T1rho_MedialWB',data_LV(1,:)) ;
T1p_lat_row_LV = strmatch('T1rho_LateralWB',data_LV(1,:)) ;
T2_med_row_LV = strmatch('T2_MedialWB',data_LV(1,:)) ;
T2_lat_row_LV = strmatch('T2_LateralWB',data_LV(1,:)) ;
T1p_med_row_PW = strmatch('T1rho_MedialWB',data_PW(1,:)) ;
T1p_lat_row_PW = strmatch('T1rho_LateralWB',data_PW(1,:)) ;
T2_med_row_PW = strmatch('T2_MedialWB',data_PW(1,:)) ;
T2_lat_row_PW = strmatch('T2_LateralWB',data_PW(1,:)) ;

T1p_med_LV_in = cell2mat(data_LV(2:end,T1p_med_row_LV)) ;
T1p_lat_LV_in = cell2mat(data_LV(2:end,T1p_lat_row_LV)) ;
T2_med_LV_in = cell2mat(data_LV(2:end,T2_med_row_LV)) ;
T2_lat_LV_in = cell2mat(data_LV(2:end,T2_lat_row_LV)) ;
T1p_med_PW_in = cell2mat(data_PW(2:end,T1p_med_row_PW)) ;
T1p_lat_PW_in = cell2mat(data_PW(2:end,T1p_lat_row_PW)) ;
T2_med_PW_in = cell2mat(data_PW(2:end,T2_med_row_PW)) ;
T2_lat_PW_in = cell2mat(data_PW(2:end,T2_lat_row_PW)) ;

dT2_med_PW = zeros(nSubs,1) ;
dT1p_med_PW = zeros(nSubs,1) ;
T2_med_LV = zeros(nSubs,2) ;
T1p_med_LV = zeros(nSubs,2) ;
dT2_lat_PW = zeros(nSubs,1) ;
dT1p_lat_PW = zeros(nSubs,1) ;
T2_lat_LV = zeros(nSubs,2) ;
T1p_lat_LV = zeros(nSubs,2) ;

for i = 1:nSubs
    sub = subjects(i) ;
    % Fill LV array
    if ismember(sub,sub_LV)
        wk1 = find(sub_LV==sub & week_LV==1) ;
        wk52 = find(sub_LV==sub & week_LV==52) ;
        T2_med_LV(i,1:2) = [T2_med_LV_in(wk1) T2_med_LV_in(wk52)] ;
        T2_lat_LV(i,1:2) = [T2_lat_LV_in(wk1) T2_lat_LV_in(wk52)] ;
        T1p_med_LV(i,1:2) = [T1p_med_LV_in(wk1) T1p_med_LV_in(wk52)] ;
        T1p_lat_LV(i,1:2) = [T1p_lat_LV_in(wk1) T1p_lat_LV_in(wk52)] ;
    else
        T2_med_LV(i,1:2) = [nan nan] ;
        T1p_med_LV(i,1:2) = [nan nan] ;
        T2_lat_LV(i,1:2) = [nan nan] ;
        T1p_lat_LV(i,1:2) = [nan nan] ;
    end
    
    % Fill PW array
    if ismember(sub,sub_PW)
        rowInd = find(sub_PW==sub) ;
        dT2_med_PW(i) = T2_med_PW_in(rowInd) ;
        dT2_lat_PW(i) = T2_lat_PW_in(rowInd) ;
        dT1p_med_PW(i) = T1p_med_PW_in(rowInd) ;
        dT1p_lat_PW(i) = T1p_lat_PW_in(rowInd) ;
    else
        dT2_med_PW(i) = nan ;
        dT2_lat_PW(i) = nan ;
        dT1p_med_PW(i) = nan ;
        dT1p_lat_PW(i) = nan ;
    end
end

% fill structReturn structure with results
OUT.longitudinal.T1p_med = T1p_med_LV ;
OUT.longitudinal.T1p_lat = T1p_lat_LV ;
OUT.longitudinal.T2_med = T2_med_LV ;
OUT.longitudinal.T2_lat = T2_lat_LV ;
OUT.longitudinal.dT1p_med = diff(T1p_med_LV,1,2) ;
OUT.longitudinal.dT1p_lat = diff(T1p_lat_LV,1,2) ;
OUT.longitudinal.dT2_med = diff(T2_med_LV,1,2) ;
OUT.longitudinal.dT2_lat = diff(T2_lat_LV,1,2) ;

OUT.pixelwise.T1p_med = dT1p_med_PW ;
OUT.pixelwise.T1p_lat = dT1p_lat_PW ;
OUT.pixelwise.T2_med = dT2_med_PW ;
OUT.pixelwise.T2_lat = dT2_lat_PW ;


end

function c = repEmptyNan(myCell)
    fx=@(x)isempty(x) ;
    ind=cellfun(fx,myCell) ;
    c(find(ind))={nan} ;
    c(find(~ind)) = myCell(find(~ind)) ;
end

function c = removeR(myCell)
    fx=@(x)(x(2:end)) ;
    c=cellfun(fx,myCell,'UniformOutput',false) ;
end
